# Generated by Django 2.1.8 on 2019-06-23 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='databaseaccess',
            old_name='db',
            new_name='animaldb',
        ),
        migrations.AlterUniqueTogether(
            name='databaseaccess',
            unique_together={('group', 'animaldb')},
        ),
    ]
