# Generated by Django 2.1.8 on 2019-06-17 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190617_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='access_fishdb',
            field=models.BooleanField(default=False, verbose_name='can access FishDB'),
        ),
        migrations.AddField(
            model_name='group',
            name='access_flydb',
            field=models.BooleanField(default=False, verbose_name='can access FishDB'),
        ),
        migrations.AddField(
            model_name='group',
            name='access_rodentdb',
            field=models.BooleanField(default=False, verbose_name='can access FishDB'),
        ),
    ]
