# Generated by Django 2.1.8 on 2019-06-17 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20190617_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='access_fishdb',
            field=models.BooleanField(default=False, verbose_name='can access Fish DB'),
        ),
        migrations.AlterField(
            model_name='group',
            name='access_flydb',
            field=models.BooleanField(default=False, verbose_name='can access Fly DB'),
        ),
        migrations.AlterField(
            model_name='group',
            name='access_rodentdb',
            field=models.BooleanField(default=False, verbose_name='can access Rodent DB'),
        ),
    ]
