# Generated by Django 2.1.8 on 2019-08-02 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_display_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='databaseaccess',
            name='animaldb',
            field=models.CharField(choices=[('fishdb', 'Fish DB'), ('flydb', 'Fly DB'), ('rodentdb', 'Rodent DB')], max_length=10, verbose_name='Database'),
        ),
        migrations.AlterField(
            model_name='databaseaccess',
            name='level',
            field=models.CharField(choices=[('admin', 'Group members can manage all entries'), ('basic', 'Group members can only manage their own entries'), ('view', 'Group members can only view')], default='view', max_length=6, verbose_name='Access level'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='is_manager',
            field=models.BooleanField(default=False, help_text='Designates whether the user has permissions to manage all group entries in the database.', verbose_name='Manager'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='is_responsible',
            field=models.BooleanField(default=False, help_text='Designates whether the user is the POC.', verbose_name='Responsible'),
        ),
    ]
