# Generated by Django 2.1.8 on 2019-06-17 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20190617_1700'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='access_fishdb',
            new_name='can_access_fishdb',
        ),
        migrations.RenameField(
            model_name='group',
            old_name='access_flydb',
            new_name='can_access_flydb',
        ),
        migrations.RenameField(
            model_name='group',
            old_name='access_rodentdb',
            new_name='can_access_rodentdb',
        ),
    ]
