# Generated by Django 2.2.5 on 2019-09-26 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_group_institution'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Institution',
        ),
    ]
