# Generated by Django 2.1.8 on 2019-06-17 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20190617_1700'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatabaseAccess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db', models.CharField(choices=[('a', 'A')], max_length=10)),
                ('is_staff', models.BooleanField(default=False, verbose_name='staff status')),
            ],
        ),
        migrations.AddField(
            model_name='group',
            name='dbs',
            field=models.ManyToManyField(to='users.DatabaseAccess'),
        ),
    ]
