# Generated by Django 2.2.7 on 2020-01-29 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_delete_institution'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'ordering': ['name']},
        ),
    ]
