# Generated by Django 2.1.8 on 2019-06-17 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20190617_1834'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='dbs',
        ),
        migrations.AddField(
            model_name='databaseaccess',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.Group'),
            preserve_default=False,
        ),
    ]
