# Generated by Django 2.1.8 on 2019-06-17 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20190617_1836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='databaseaccess',
            name='db',
            field=models.CharField(choices=[('fishdb', 'Fish DB'), ('flydb', 'Fly DB'), ('rodentdb', 'Rodent DB')], max_length=10),
        ),
    ]
