# Generated by Django 2.2.11 on 2020-03-11 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20200129_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='is_manager',
            field=models.BooleanField(default=False, help_text='Designates whether the user has permissions to manage group info and all group entries in the database.', verbose_name='Manager'),
        ),
    ]
