# Generated by Django 2.1.8 on 2019-06-17 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20190617_1857'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='databaseaccess',
            unique_together={('group', 'db')},
        ),
    ]
