# Generated by Django 2.1.8 on 2019-06-17 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20190617_1900'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='can_access_fishdb',
        ),
        migrations.RemoveField(
            model_name='group',
            name='can_access_flydb',
        ),
        migrations.RemoveField(
            model_name='group',
            name='can_access_rodentdb',
        ),
    ]
