# Generated by Django 2.1.8 on 2019-06-17 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20190617_1907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='databaseaccess',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Designates whether the group can manage this DB.', verbose_name='staff status'),
        ),
    ]
