# Generated by Django 2.1.8 on 2019-06-17 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20190617_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='databaseaccess',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accesses', to='users.Group'),
        ),
    ]
