# Generated by Django 2.1.8 on 2019-06-19 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_group_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='databaseaccess',
            options={'verbose_name': 'database access', 'verbose_name_plural': 'database accesses'},
        ),
    ]
