# Generated by Django 2.1.8 on 2019-06-19 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_auto_20190619_1906'),
    ]

    operations = [
        migrations.AddField(
            model_name='databaseaccess',
            name='level',
            field=models.CharField(choices=[('admin', 'Administrator'), ('basic_users', 'Basic Users'), ('view_only', 'View Only')], default='basic_users', max_length=11),
        ),
    ]
