# Generated by Django 2.1.8 on 2019-06-19 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_databaseaccess_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='databaseaccess',
            name='is_staff',
        ),
    ]
