# Generated by Django 2.1.8 on 2019-06-19 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_remove_databaseaccess_is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='databaseaccess',
            name='level',
            field=models.CharField(choices=[('admin', 'Administrator'), ('basic_users', 'Basic Users'), ('view_only', 'View Only')], default='basic_users', max_length=11, verbose_name='access level'),
        ),
    ]
