# Generated by Django 2.1.8 on 2019-06-19 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_auto_20190619_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='databaseaccess',
            name='db',
            field=models.CharField(choices=[('fishdb', 'Fish DB'), ('flydb', 'Fly DB'), ('rodentdb', 'Rodent DB')], max_length=10, verbose_name='database'),
        ),
    ]
