# Generated by Django 2.1.8 on 2019-06-19 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_auto_20190619_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='databaseaccess',
            name='level',
            field=models.CharField(choices=[('admin', 'Administrator'), ('basic', 'Group members can add and edit/remove their entries'), ('view_only', 'View Only')], default='basic', max_length=11, verbose_name='access level'),
        ),
    ]
