# Generated by Django 2.1.8 on 2019-06-19 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_auto_20190619_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='databaseaccess',
            name='level',
            field=models.CharField(choices=[('admin', 'Group members can manage all entries'), ('basic', 'Group members can add and edit/remove their entries only'), ('view', 'Group members can only view')], default='basic', max_length=11, verbose_name='access level'),
        ),
    ]
