# Generated by Django 2.1.8 on 2019-06-21 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_auto_20190621_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='databaseaccess',
            name='level',
            field=models.CharField(choices=[('admin', 'Group members can manage all entries'), ('basic', 'Group members can only manage their own entries'), ('view', 'Group members can only view')], default='view', max_length=6, verbose_name='access level'),
        ),
    ]
