# Generated by Django 2.1.12 on 2019-09-18 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('availability', models.CharField(choices=[('live', 'Live'), ('cryo', 'Cryopreserved'), ('both', 'Live & Cryopreserved'), ('none', 'Unavailable')], max_length=4)),
                ('link', models.URLField(blank=True)),
                ('strain_name', models.CharField(max_length=255)),
                ('common_name', models.CharField(blank=True, max_length=50)),
                ('background', models.CharField(max_length=30)),
                ('genotype', models.CharField(max_length=30)),
                ('phenotype', models.CharField(max_length=30)),
                ('origin', models.CharField(blank=True, help_text='Leave blank for in-house generated lines', max_length=80, verbose_name='Imported from')),
                ('quarantine', models.BooleanField(default=False, verbose_name='Quarantine')),
                ('mta', models.BooleanField(default=True, verbose_name='MTA')),
                ('line_description', models.TextField(blank=True)),
                ('category_name', models.CharField(max_length=40)),
                ('species_name', models.CharField(max_length=80)),
                ('remote_id', models.BigIntegerField(verbose_name='Remote id')),
            ],
        ),
        migrations.CreateModel(
            name='Fly',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('categories', models.TextField(blank=True, null=True, verbose_name='Category')),
                ('species', models.CharField(max_length=80, verbose_name='Species')),
                ('origin', models.CharField(choices=[('center', 'Stock Center'), ('internal', 'Internal Lab'), ('external', 'External Lab')], default='center', max_length=8)),
                ('origin_center', models.CharField(blank=True, max_length=100, null=True, verbose_name='Species')),
                ('genotype', models.CharField(blank=True, max_length=255, verbose_name='Genotype')),
                ('chrx', models.CharField(blank=True, max_length=60, verbose_name='Chromosome X')),
                ('chry', models.CharField(blank=True, max_length=60, verbose_name='Chromosome Y')),
                ('chr2', models.CharField(blank=True, max_length=60, verbose_name='Chromosome 2')),
                ('chr3', models.CharField(blank=True, max_length=60, verbose_name='Chromosome 3')),
                ('chr4', models.CharField(blank=True, max_length=60, verbose_name='Chromosome 4')),
                ('bal1', models.CharField(blank=True, max_length=60, verbose_name='Balancer 1')),
                ('bal2', models.CharField(blank=True, max_length=60, verbose_name='Balancer 2')),
                ('bal3', models.CharField(blank=True, max_length=60, verbose_name='Balancer 3')),
                ('chru', models.CharField(blank=True, max_length=60, verbose_name='Unknown genotype')),
                ('special_husbandry_conditions', models.TextField(blank=True)),
                ('line_description', models.TextField(blank=True)),
                ('remote_id', models.BigIntegerField(verbose_name='Remote id')),
                ('institution_name', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MissedSync',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('object_id', models.IntegerField(verbose_name='Object id')),
                ('operation', models.CharField(choices=[('D', 'Delete'), ('U', 'Update')], max_length=1, verbose_name='Operation')),
                ('committed', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Committed on')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('contenttype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType', verbose_name='Table')),
            ],
        ),
        migrations.CreateModel(
            name='Rodent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('availability', models.CharField(choices=[('live', 'Live'), ('cryo', 'Cryopreserved'), ('both', 'Live & Cryopreserved'), ('none', 'Unavailable')], max_length=4)),
                ('link', models.URLField(blank=True)),
                ('species', models.CharField(max_length=80)),
                ('strain_name', models.CharField(max_length=20)),
                ('common_name', models.CharField(max_length=20)),
                ('origin', models.CharField(max_length=40)),
                ('origin_other', models.CharField(blank=True, max_length=40)),
                ('category', models.CharField(max_length=40)),
                ('background', models.CharField(blank=True, max_length=80, null=True)),
                ('zygosity', models.CharField(blank=True, max_length=20)),
                ('line_description', models.TextField(blank=True)),
                ('coat_color', models.CharField(blank=True, max_length=40, null=True)),
                ('reporter_gene', models.CharField(blank=True, max_length=40, null=True)),
                ('inducible_cassette', models.CharField(blank=True, max_length=40, null=True)),
                ('remote_id', models.BigIntegerField(verbose_name='Remote id')),
            ],
        ),
    ]
