# Generated by Django 2.1.12 on 2019-09-24 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('congentodb_client', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fly',
            name='categories',
            field=models.TextField(blank=True, default='', verbose_name='Category'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fly',
            name='institution_name',
            field=models.CharField(blank=True, default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fly',
            name='origin_center',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Stock center'),
            preserve_default=False,
        ),
    ]
