# Generated by Django 2.2.1 on 2019-05-11 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('congentodb_client', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='missedsync',
            old_name='opperation',
            new_name='operation',
        ),
        migrations.AddField(
            model_name='missedsync',
            name='object_id',
            field=models.IntegerField(default=None, verbose_name='Object id'),
            preserve_default=False,
        ),
    ]
