# Generated by Django 2.1.12 on 2019-09-24 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('congentodb_client', '0002_auto_20190924_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fly',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
