# Generated by Django 2.1.11 on 2019-09-17 17:15

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('congentodb_client', '0002_auto_20190511_1832'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rodent',
            old_name='comments',
            new_name='line_description',
        ),
        migrations.RemoveField(
            model_name='rodent',
            name='background_other',
        ),
        migrations.RemoveField(
            model_name='rodent',
            name='genotype',
        ),
        migrations.RemoveField(
            model_name='rodent',
            name='genotype_other',
        ),
        migrations.RemoveField(
            model_name='rodent',
            name='institution_name',
        ),
        migrations.RemoveField(
            model_name='rodent',
            name='model_type',
        ),
        migrations.RemoveField(
            model_name='rodent',
            name='model_type_other',
        ),
        migrations.RemoveField(
            model_name='rodent',
            name='mta',
        ),
        migrations.AddField(
            model_name='rodent',
            name='category',
            field=models.CharField(default=datetime.datetime(2019, 9, 17, 17, 15, 26, 103237, tzinfo=utc), max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rodent',
            name='coat_color',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='rodent',
            name='inducible_cassette',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='rodent',
            name='origin_other',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='rodent',
            name='reporter_gene',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='rodent',
            name='zygosity',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='missedsync',
            name='contenttype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType', verbose_name='Table'),
        ),
        migrations.AlterField(
            model_name='rodent',
            name='background',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='rodent',
            name='origin',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='rodent',
            name='species',
            field=models.CharField(max_length=80),
        ),
    ]
