# Generated by Django 2.1.12 on 2019-09-24 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('congentodb_client', '0003_auto_20190924_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fly',
            name='remote_id',
            field=models.BigIntegerField(verbose_name='Remote ID'),
        ),
    ]
