# Generated by Django 2.1.12 on 2019-09-25 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('congentodb_client', '0004_auto_20190924_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rodent',
            name='background',
            field=models.CharField(blank=True, default='', max_length=80),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rodent',
            name='coat_color',
            field=models.CharField(blank=True, default='', max_length=40),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rodent',
            name='inducible_cassette',
            field=models.CharField(blank=True, default='', max_length=40),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rodent',
            name='remote_id',
            field=models.BigIntegerField(verbose_name='Remote ID'),
        ),
        migrations.AlterField(
            model_name='rodent',
            name='reporter_gene',
            field=models.CharField(blank=True, default='', max_length=40),
            preserve_default=False,
        ),
    ]
