# Generated by Django 2.1.12 on 2019-09-25 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('congentodb_client', '0005_auto_20190925_1433'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fish',
            options={'verbose_name': 'Fish', 'verbose_name_plural': 'Fish'},
        ),
        migrations.AlterModelOptions(
            name='fly',
            options={'verbose_name': 'Fly', 'verbose_name_plural': 'Flies'},
        ),
        migrations.AlterModelOptions(
            name='missedsync',
            options={'verbose_name': 'Failed synchronization', 'verbose_name_plural': 'Failed synchronizations'},
        ),
        migrations.AlterModelOptions(
            name='rodent',
            options={'verbose_name': 'Rodent', 'verbose_name_plural': 'Rodents'},
        ),
    ]
