# Generated by Django 2.2.5 on 2019-09-26 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('congentodb_client', '0006_auto_20190925_1446'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fly',
            name='institution_name',
        ),
    ]
